// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mijalski.EntityFrameworkCore;

namespace Mijalski.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200109205328_seed-data2")]
    partial class seeddata2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.GraphicCards.GraphicCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterfaceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProcessorSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Wattage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("VendorId");

                    b.ToTable("AppGraphicCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb58d505-e983-43a0-bded-44f9ec8e45ef"),
                            CreationDateTime = new DateTime(2020, 1, 9, 20, 53, 27, 185, DateTimeKind.Utc).AddTicks(9890),
                            InterfaceType = "PCI Express 3.0",
                            Name = "GTX 970",
                            Price = 330m,
                            ProcessorSpeed = "1753MHz",
                            VendorId = new Guid("3abfbdc1-4f55-4251-b91f-e47f811f6658"),
                            Wattage = 145.0
                        },
                        new
                        {
                            Id = new Guid("863e110e-756e-4f4f-a71c-9242e1e4695f"),
                            CreationDateTime = new DateTime(2020, 1, 9, 20, 53, 27, 186, DateTimeKind.Utc).AddTicks(5247),
                            InterfaceType = "PCI Express 3.0",
                            Name = "RTX 2070 Super",
                            Price = 609m,
                            ProcessorSpeed = "1605Mhz + Boost",
                            VendorId = new Guid("3abfbdc1-4f55-4251-b91f-e47f811f6658"),
                            Wattage = 160.0
                        });
                });

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.Specs.Ram", b =>
                {
                    b.Property<Guid>("GraphicCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfRam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GraphicCardId");

                    b.ToTable("AppRams");

                    b.HasData(
                        new
                        {
                            GraphicCardId = new Guid("bb58d505-e983-43a0-bded-44f9ec8e45ef"),
                            Capacity = 8,
                            TypeOfRam = "GDDR6"
                        },
                        new
                        {
                            GraphicCardId = new Guid("863e110e-756e-4f4f-a71c-9242e1e4695f"),
                            Capacity = 8,
                            TypeOfRam = "GDDR5"
                        });
                });

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.Vendors.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AppVendors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3abfbdc1-4f55-4251-b91f-e47f811f6658"),
                            CreationDateTime = new DateTime(2020, 1, 9, 20, 53, 27, 185, DateTimeKind.Utc).AddTicks(4266),
                            Name = "Nvidia"
                        });
                });

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.GraphicCards.GraphicCard", b =>
                {
                    b.HasOne("Mijalski.EntityFrameworkCore.Business.Vendors.Vendor", "Vendor")
                        .WithMany("GraphicCards")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.Specs.Ram", b =>
                {
                    b.HasOne("Mijalski.EntityFrameworkCore.Business.GraphicCards.GraphicCard", null)
                        .WithOne("Ram")
                        .HasForeignKey("Mijalski.EntityFrameworkCore.Business.Specs.Ram", "GraphicCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
