// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mijalski.EntityFrameworkCore;

namespace Mijalski.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.GraphicCards.GraphicCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterfaceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProcessorSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Wattage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("VendorId");

                    b.ToTable("AppGraphicCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e162c5fb-de2d-4a12-9048-0d5173b5b988"),
                            CreationDateTime = new DateTime(2020, 1, 9, 20, 54, 50, 691, DateTimeKind.Utc).AddTicks(4295),
                            InterfaceType = "PCI Express 3.0",
                            Name = "GTX 970",
                            Price = 330m,
                            ProcessorSpeed = "1753MHz",
                            VendorId = new Guid("a4fa85c5-017c-4d28-b6cd-396da935cc58"),
                            Wattage = 145.0
                        },
                        new
                        {
                            Id = new Guid("a0a785d4-9aee-4184-bca2-2b826b08a0b3"),
                            CreationDateTime = new DateTime(2020, 1, 9, 20, 54, 50, 695, DateTimeKind.Utc).AddTicks(9565),
                            InterfaceType = "PCI Express 3.0",
                            Name = "RTX 2070 Super",
                            Price = 609m,
                            ProcessorSpeed = "1605Mhz + Boost",
                            VendorId = new Guid("a4fa85c5-017c-4d28-b6cd-396da935cc58"),
                            Wattage = 160.0
                        });
                });

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.Specs.Ram", b =>
                {
                    b.Property<Guid>("GraphicCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfRam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GraphicCardId");

                    b.ToTable("AppRams");

                    b.HasData(
                        new
                        {
                            GraphicCardId = new Guid("e162c5fb-de2d-4a12-9048-0d5173b5b988"),
                            Capacity = 4,
                            TypeOfRam = "GDDR5"
                        },
                        new
                        {
                            GraphicCardId = new Guid("a0a785d4-9aee-4184-bca2-2b826b08a0b3"),
                            Capacity = 8,
                            TypeOfRam = "GDDR5"
                        });
                });

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.Vendors.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("AppVendors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4fa85c5-017c-4d28-b6cd-396da935cc58"),
                            CreationDateTime = new DateTime(2020, 1, 9, 20, 54, 50, 690, DateTimeKind.Utc).AddTicks(9271),
                            Name = "Nvidia"
                        });
                });

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.GraphicCards.GraphicCard", b =>
                {
                    b.HasOne("Mijalski.EntityFrameworkCore.Business.Vendors.Vendor", "Vendor")
                        .WithMany("GraphicCards")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mijalski.EntityFrameworkCore.Business.Specs.Ram", b =>
                {
                    b.HasOne("Mijalski.EntityFrameworkCore.Business.GraphicCards.GraphicCard", null)
                        .WithOne("Ram")
                        .HasForeignKey("Mijalski.EntityFrameworkCore.Business.Specs.Ram", "GraphicCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
